# fly.toml app configuration file generated for votingserver on 2023-07-07T00:12:19+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "votingserver"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
