# fly.toml app configuration file generated for votingappserver on 2023-06-29T14:18:40+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "votingappserver"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
